version: '3'

networks:
  kafka-golang_default:
    external: true

services:

  sqs:
    image: localstack/localstack
    ports:
      - "4576:4576"
      - "8080:8080"
    environment:
      - SERVICES=sqs

#  consumer:
#    container_name: go-consumer
#    build: '.'
#    environment:
#      TOPIC: events
#      BROKER_SRV: broker
#      BROKER_PORT: 9092
#      GROUP: consumers
#    depends_on:
#    - sqs
#    networks:
#      - kafka-golang_default
#    restart: always
